#!/bin/bash
# threeandout-develop daemon
# chkconfig: 345 20 80
# description: threeandout-develop daemon
# processname: threeandout-develop

DAEMON_PATH="/data/test/threeandout/threeandout"

DAEMON="python manage.py runserver 0.0.0.0:8001"
DAEMONOPTS="-settings=threeandout.settings.dev"

NAME=threeandout-develop
DESC="My daemon description"
PIDFILE=/var/run/$NAME.pid
SCRIPTNAME=/etc/init.d/$NAME
LOGFILE=/var/tmp/$NAME.log
RUNUSER=ops
VENVFILE=/home/ops/.virtualenvs/develop/bin/activate

case "$1" in
start)
        printf "%-50s" "Starting $NAME..."
        PID=`su ops -c '/home/ops/start-dev.sh'`
        echo "Saving PID" $PID " to " $PIDFILE
        if [ -z $PID ]; then
            printf "%s\n" "Fail"
        else
            echo $PID > $PIDFILE
            printf "%s\n" "Ok"
        fi
;;
status)
        printf "%-50s" "Checking $NAME..."
        if [ -f $PIDFILE ]; then
            PID=`cat $PIDFILE`
            if [ -z "`ps axf | grep ${PID} | grep -v grep`" ]; then
                printf "%s\n" "Process dead but pidfile exists"
            else
                echo "Running"
            fi
        else
            printf "%s\n" "Service not running"
        fi
;;
stop)
        printf "%-50s" "Stopping $NAME"
            PID=`cat $PIDFILE`
            cd $DAEMON_PATH
        if [ -f $PIDFILE ]; then
            pkill -P $PID
            printf "%s\n" "Ok"
            rm -f $PIDFILE
        else
            printf "%s\n" "pidfile not found"
        fi
;;

restart)
        $0 stop
        $0 start
;;

*)
        echo "Usage: $0 {status|start|stop|restart}"
        exit 1
esac



