import sys
sys.path.append('../threeandout')
import os
if not os.environ.has_key('DJANGO_SETTINGS_MODULE'):
  os.environ['DJANGO_SETTINGS_MODULE'] = 'threeandout.settings.dev'
import threeandout.apps.ff_core.models as models
import datetime
import pytz

if __name__=="__main__":
    
    team = models.NFLTeam(city="Chicago", name="Bears", short_name="CHI")
    team.save()    
    team = models.NFLTeam(city="Arizona", name="Cardinals", short_name="ARI")
    team.save()
    team = models.NFLTeam(city="Green Bay", name="Packers", short_name="GB")
    team.save()
    team = models.NFLTeam(city="New York", name="Giants", short_name="NYG")
    team.save() 
    team = models.NFLTeam(city="Detroit", name="Lions", short_name="DET")
    team.save()
    team = models.NFLTeam(city="Washington", name="Redskins", short_name="WAS")
    team.save()
    team = models.NFLTeam(city="Pittsburgh", name="Steelers", short_name="PIT")
    team.save()
    team = models.NFLTeam(city="Philadelphia", name="Eagles", short_name="PHI")
    team.save()
    team = models.NFLTeam(city="St. Louis", name="Rams", short_name="STL")
    team.save()
    team = models.NFLTeam(city="San Francisco", name="49ers", short_name="SF")
    team.save()
    team = models.NFLTeam(city="Cleveland", name="Browns", short_name="CLE")
    team.save()
    team = models.NFLTeam(city="Indianapolis", name="Colts", short_name="IND")
    team.save()
    team = models.NFLTeam(city="Dallas", name="Cowboys", short_name="DAL")
    team.save()
    team = models.NFLTeam(city="Oakland", name="Raiders", short_name="OAK")
    team.save()
    team = models.NFLTeam(city="New England", name="Patriots", short_name="NE")
    team.save()
    team = models.NFLTeam(city="Tennessee", name="Titans", short_name="TEN")
    team.save()
    team = models.NFLTeam(city="Denver", name="Broncos", short_name="DEN")
    team.save()
    team = models.NFLTeam(city="San Diego", name="Chargers", short_name="SD")
    team.save()
    team = models.NFLTeam(city="New York", name="Jets", short_name="NYJ")
    team.save()
    team = models.NFLTeam(city="Kansas City", name="Chiefs", short_name="KC")
    team.save()
    team = models.NFLTeam(city="Buffalo", name="Bills", short_name="BUF")
    team.save() 
    team = models.NFLTeam(city="Minnesota", name="Vikings", short_name="MIN")
    team.save()   
    team = models.NFLTeam(city="Miami", name="Dolphins", short_name="MIA")
    team.save()
    team = models.NFLTeam(city="Atlanta", name="Falcons", short_name="ATL")
    team.save()
    team = models.NFLTeam(city="New Orleans", name="Saints", short_name="NO")
    team.save()
    team = models.NFLTeam(city="Cincinnati", name="Bengals", short_name="CIN")
    team.save()
    team = models.NFLTeam(city="Seattle", name="Seahawks", short_name="SEA")
    team.save()
    team = models.NFLTeam(city="Tampa Bay", name="Buccaneers", short_name="TB")
    team.save()
    team = models.NFLTeam(city="Jacksonville", name="Jaguars", short_name="JAX")
    team.save() 
    team = models.NFLTeam(city="Carolina", name="Panthers", short_name="CAR")
    team.save() 
    team = models.NFLTeam(city="Baltimore", name="Ravens", short_name="BAL")
    team.save()
    team = models.NFLTeam(city="Houston", name="Texans", short_name="HOU")
    team.save()
